name: Static Code Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    name: Analyze Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run Roslynator
      run: dotnet roslynator analyze --fix

    # Optionally, you can add additional steps to run StyleCop or other static analysis tools
